In [1]:
import pandas as pd
import numpy as np
import json
import torch

In [2]:
path = 'anupp/250216_ANNuPP_feature_vectors.csv'
df = pd.read_csv(path).set_index('amino_acid')
df

C  N  O  Ca  Cb  Cg  Cg1  Cg2  Cd  Cd1  ...  Nz  Od1  Od2  Oe1  \
amino_acid                                          ...                      
A           1  1  1   1   1   0    0    0   0    0  ...   0    0    0    0   
C           1  1  1   1   1   0    0    0   0    0  ...   0    0    0    0   
D           1  1  1   1   1   1    0    0   0    0  ...   0    1    1    0   
E           1  1  1   1   1   1    0    0   1    0  ...   0    0    0    1   
F           1  1  1   1   1   1    0    0   0    1  ...   0    0    0    0   
G           1  1  1   1   0   0    0    0   0    0  ...   0    0    0    0   
H           1  1  1   1   1   1    0    0   0    0  ...   0    0    0    0   
I           1  1  1   1   1   0    1    1   0    1  ...   0    0    0    0   
K           1  1  1   1   1   1    0    0   1    0  ...   1    0    0    0   
L           1  1  1   1   1   1    0    0   0    1  ...   0    0    0    0   
M           1  1  1   1   1   1    0    0   0    0  ...   0    0    0    0   
N           1  1  1   1   1   1    0    0   0    0  ...   0    1    0    0   
P           1  1  1   1   1   1    0    0   1    0  ...   0    0    0    0   
Q           1  1  1   1   1   1    0    0   1    0  ...   0    0    0    1   
R           1  1  1   1   1   1    0    0   1    0  ...   0    0    0    0   
S           1  1  1   1   1   0    0    0   0    0  ...   0    0    0    0   
T           1  1  1   1   1   0    0    1   0    0  ...   0    0    0    0   
V           1  1  1   1   1   0    1    1   0    0  ...   0    0    0    0   
W           1  1  1   1   1   1    0    0   0    1  ...   0    0    0    0   
Y           1  1  1   1   1   1    0    0   0    1  ...   0    0    0    0   

            Oe2  Og  Og1  Oh  Sd  Sg  
amino_acid                            
A             0   0    0   0   0   0  
C             0   0    0   0   0   1  
D             0   0    0   0   0   0  
E             1   0    0   0   0   0  
F             0   0    0   0   0   0  
G             0   0    0   0   0   0  
H             0   0    0   0   0   0  
I             0   0    0   0   0   0  
K             0   0    0   0   0   0  
L             0   0    0   0   0   0  
M             0   0    0   0   1   0  
N             0   0    0   0   0   0  
P             0   0    0   0   0   0  
Q             0   0    0   0   0   0  
R             0   0    0   0   0   0  
S             0   1    0   0   0   0  
T             0   0    1   0   0   0  
V             0   0    0   0   0   0  
W             0   0    0   0   0   0  
Y             0   0    0   1   0   0  

[20 rows x 36 columns]

In [3]:
anupp_dict = dict()
for aa,row in df.iterrows():
    anupp_dict[aa] = list(row)

with open('anupp/250216_ANNuPP_feature_vectors.json','w') as file:
    json.dump(anupp_dict,file)

In [4]:
print(anupp_dict)

{'A': [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'C': [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], 'D': [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0], 'E': [1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0], 'F': [1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'G': [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'H': [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'I': [1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'K': [1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [5]:
test_seq = 'RSFFSFLGEAFDGARDMWRAYSDMREANYIGSDKYFHARGNYDAAKRGPGGVWAAEAISDARENIQRFFGHGAEDSLADQAANEWGRSGKDPNHFRPAGLPEKY'
feature_list = []
for char in test_seq:
    feature_list.append(anupp_dict[char])
seq_features = torch.tensor(feature_list,dtype=float)
seq_features

tensor([[1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 1., 0., 0.]], dtype=torch.float64)

In [10]:
sequence_embeddings = torch.stack([x.mean(dim=0) for x in seq_features])
sequence_embeddings.numpy()

array([0.30555556, 0.16666667, 0.30555556, 0.30555556, 0.16666667,
       0.30555556, 0.22222222, 0.11111111, 0.25      , 0.13888889,
       0.30555556, 0.22222222, 0.11111111, 0.13888889, 0.30555556,
       0.22222222, 0.22222222, 0.38888889, 0.30555556, 0.13888889,
       0.33333333, 0.16666667, 0.22222222, 0.22222222, 0.30555556,
       0.25      , 0.13888889, 0.22222222, 0.33333333, 0.22222222,
       0.11111111, 0.16666667, 0.22222222, 0.25      , 0.33333333,
       0.30555556, 0.27777778, 0.13888889, 0.30555556, 0.11111111,
       0.22222222, 0.33333333, 0.22222222, 0.13888889, 0.13888889,
       0.25      , 0.30555556, 0.11111111, 0.19444444, 0.11111111,
       0.11111111, 0.19444444, 0.38888889, 0.13888889, 0.13888889,
       0.25      , 0.13888889, 0.22222222, 0.16666667, 0.22222222,
       0.13888889, 0.30555556, 0.25      , 0.22222222, 0.22222222,
       0.25      , 0.30555556, 0.30555556, 0.30555556, 0.11111111,
       0.27777778, 0.11111111, 0.13888889, 0.25      , 0.22222

In [15]:
sequences = [test_seq,test_seq]

In [19]:
test = [torch.tensor([anupp_dict[char] for char in seq],dtype=float) for seq in sequences]
test

[tensor([[1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 1., 0., 0.]], dtype=torch.float64),
 tensor([[1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 1., 0., 0.]], dtype=torch.float64)]

In [20]:
sequence_embeddings = torch.stack([x.mean(dim=0) for x in test])
sequence_embeddings.numpy()

array([[1.        , 1.        , 1.        , 1.        , 0.88461538,
        0.625     , 0.03846154, 0.03846154, 0.25961538, 0.21153846,
        0.21153846, 0.05769231, 0.15384615, 0.15384615, 0.02884615,
        0.02884615, 0.22115385, 0.02884615, 0.02884615, 0.02884615,
        0.04807692, 0.09615385, 0.02884615, 0.04807692, 0.09615385,
        0.09615385, 0.03846154, 0.13461538, 0.08653846, 0.08653846,
        0.06730769, 0.06730769, 0.        , 0.04807692, 0.01923077,
        0.        ],
       [1.        , 1.        , 1.        , 1.        , 0.88461538,
        0.625     , 0.03846154, 0.03846154, 0.25961538, 0.21153846,
        0.21153846, 0.05769231, 0.15384615, 0.15384615, 0.02884615,
        0.02884615, 0.22115385, 0.02884615, 0.02884615, 0.02884615,
        0.04807692, 0.09615385, 0.02884615, 0.04807692, 0.09615385,
        0.09615385, 0.03846154, 0.13461538, 0.08653846, 0.08653846,
        0.06730769, 0.06730769, 0.        , 0.04807692, 0.01923077,
        0.        ]])

In [21]:
from abc import ABC, abstractmethod

class AbstractClass(ABC):
    @property
    @abstractmethod
    def my_property(self):
        pass

class DerivedClass(AbstractClass):
    @property
    def my_property(self):
        return "Property value from DerivedClass"

# Usage
obj = DerivedClass()
print(obj.my_property)  # Output: Property value from DerivedClass

Property value from DerivedClass
